server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/payment-service-db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:changelog/changelog-master.xml
spring.liquibase.drop-first=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/PaycardSystem
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/PaycardSystem/protocol/openid-connect/certs

application.config.user-service-url=http://localhost:8081
application.config.order-service-url=http://localhost:8082

resilience4j.circuitbreaker.instances.user-service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.user-service.slidingWindowSize=10
resilience4j.circuitbreaker.instances.user-service.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.user-service.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.user-service.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.user-service.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.user-service.failureRateThreshold=50
resilience4j.circuitbreaker.instances.user-service.eventConsumerBufferSize=10

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer